requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pyalapin"
version = "0.0.1"
authors = [
  { name = "Vincent Auriau"},
]
description = "Custom Chess Engine"
readme = "README.md"
requires-python = ">=3.8"

[tool.setuptools]
packages = [
  "tests",
  "pyalapin"
]
